### ISSUE TITLE
Some elements are not properly styled

### ISSUE THREAD

**Issue by PyvesB** [AObuchow/Eclipse-Modern-Dark-Theme#1]
I've tried the theme out, it's a good start. I like the bits of red here and there. 👍 

However, on my Windows machine at least, not all parts are being themed properly. For example in the project explorer:
![modern-dark](https://user-images.githubusercontent.com/10694593/78455100-a1380400-769c-11ea-9820-bc56d8c3d7b2.png)

I noticed you were importing `platform:/plugin/org.eclipse.ui.themes/css/dark/e4-dark_preferencestyle.css`. Maybe you're missing out on some platform-specific overrides by doing so?

Thanks for looking into this!

**Comment by AObuchow** [comment]
Wow, I wasn't expecting anyone to try this out yet! 
Thanks so much for trying it out and posting the first bug @PyvesB :)

> However, on my Windows machine at least, not all parts are being themed properly. For example in the project explorer:

Yes this is a known issue I need to fix. The theme isin't properly inheriting from the platform dark theme IIRC, thus it currently relies on the user to have a dark GTK theme (which obviously isin't feasible for Windows users).  

> I noticed you were importing `platform:/plugin/org.eclipse.ui.themes/css/dark/e4-dark_preferencestyle.css`. Maybe you're missing out on some platform-specific overrides by doing so?

This is definetly worth looking into, thanks!

> 
> Thanks for looking into this!

For sure :) I've had more time to work on side projects lately, so I've been meaning to improve this theme plugin. I'm going to try to getting to work on it sooner than later, now that you're interested 😎

**Comment by AObuchow** [comment]
@PyvesB I improved the theme but have been unable to properly update the update site ): I was trying to do it in a rush hahah, will have to try and fix it later

**Comment by AObuchow** [comment]
Nevermind.. :D
It seems that the update site works, but not if the plugin is already installed.. need to fix that.

Feel free to uninstall the plugin and reinstall using the update site in the README and let me know how it looks :) I'm going to try it out on windows in a moment.

**Comment by AObuchow** [comment]
@PyvesB It now looks a lot better on Windows, but still needs many improvements.

Here's how it looks currently (1.0.2):
![image](https://user-images.githubusercontent.com/10300119/83932655-0cbc5180-a772-11ea-8677-2a4e9f44b9ae.png)

**Comment by AObuchow** [comment]
@PyvesB A big issue with Modern Dark Theme is that the editor colours are not correctly set (as shown in the above picture). This happens despite importing the e4 dark preference style. 

A temporary workaround is to import an eclipse editor theme, but this needs to be fixed for the first official release.

**Comment by PyvesB** [comment]
Thanks @AObuchow , definitely looks much better now!

The dark menus don't aren't enabled on my side, unless I first enable the normal Dark theme then switch to Modern Dark Theme. Looking at the code in _org.eclipse.e4.ui.swt.internal.win32.DarkThemeProcessor_, I noticed the following check: `theme.getId().contains("dark")`. The theme's id is "Modern Dark Theme.id", with a capital D, so the check would fail.

As far as style sheets are concerned, according to the documentation of the theme extension point: "This extension point provides the possibility to define themes and/or contribute stylesheets and resources to already defined themes". I'm reading this as "define a style sheet if you want to modify an existing theme". As you're trying to define the styles of your own theme, I would not include it as a `<stylesheet>` element in _plugin.xml_, but instead simply have the `@import` statement in the CSS (which you do have, but it's not pointing to the version-controlled _e4-dark_preferencestyle.css_ you included in the repository). Not an expert in this area, but something worth trying. :)

**Comment by AObuchow** [comment]
> Thanks @AObuchow , definitely looks much better now!
> 
> The dark menus don't aren't enabled on my side, unless I first enable the normal Dark theme then switch to Modern Dark Theme. Looking at the code in _org.eclipse.e4.ui.swt.internal.win32.DarkThemeProcessor_, I noticed the following check: `theme.getId().contains("dark")`. The theme's id is "Modern Dark Theme.id", with a capital D, so the check would fail.

AH, you solved a big piece of the puzzle!!! Thank you so much!!

Changing the ID to contain "dark" is what enables the dark menu bar on GTK (and Windows as you mentioned)! It seems to force GTK to use dark a theme (eg. even if you are using Adwaita non-dark GTK theme, Eclipse will use Adwaita-dark). 

IMO this should be an upstream bug: instead of relying on the theme id containing the string "dark", there should be an optional extension point parameter to declare the theme as a dark or light. As it currently stands, finding out that you need to include the "dark" string in the ID is too difficult/not documented. I'll make an upstream bug for this.

I will release an update today fixing this :)

**Comment by AObuchow** [comment]
> I'll make an upstream bug for this.

Upstream bug is tracked [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564022)

**Comment by AObuchow** [comment]
> As far as style sheets are concerned, according to the documentation of the theme extension point: "This extension point provides the possibility to define themes and/or contribute stylesheets and resources to already defined themes". I'm reading this as "define a style sheet if you want to modify an existing theme". As you're trying to define the styles of your own theme, I would not include it as a `<stylesheet>` element in _plugin.xml_, but instead simply have the `@import` statement in the CSS (which you do have, but it's not pointing to the version-controlled _e4-dark_preferencestyle.css_ you included in the repository). Not an expert in this area, but something worth trying. :)

Good observation! I removed the extension point parameter and included `org.eclipse.ui.themes` in the required bundle for the manifest.

The editor colors are still incorrect, but it's a step forward :)

**Comment by PyvesB** [comment]
> 
> 
> > I'll make an upstream bug for this.
> 
> Upstream bug is tracked [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564022)

Would definitely be an improvement to have it as an extension point flag! Though I think the bug should be part of Platform UI, not SWT. :)

**Comment by AObuchow** [comment]
> Though I think the bug should be part of Platform UI, not SWT. :)

Fixed :)

Also the 1.0.3 release is out (I don't know why I didn't start with 0.0.1... the first "real" release on the eclipse marketplace will be 0.0.1. 1.0.3 fixes the dark widgets not being enabled.

There's still a lot to do: 

- For some reason, the JDT colors get set, then some colors change for some reason (I think this has to do with the colors & fonts preference in Appearance Options of the preference dialog). You can see this behavior when opening a java file (the colors will be correct for a moment then change).
- The EGit colors need to be set (a modified repo will cause a project's foreground color to be black in the project explorer)
- A bunch of other things ... :P

**Comment by AObuchow** [comment]
> There's still a lot to do:
> 
>     * For some reason, the JDT colors get set, then some colors change for some reason (I think this has to do with the colors & fonts preference in Appearance Options of the preference dialog). You can see this behavior when opening a java file (the colors will be correct for a moment then change).
> 
>     * The EGit colors need to be set (a modified repo will cause a project's foreground color to be black in the project explorer)

This was addressed in the newly release version, 1.0.4

**Comment by AObuchow** [comment]
@PyvesB are you ok with me closing this bug? More specific bugs can now be created for things that aren't properly styled, eg. https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/issues/32

**Comment by PyvesB** [comment]
Sure! I've not got much time to test with my personal Windows machine at the moment, but I'll install it on my macOS work machine and see if I spot anything wrong. 😉

**Comment by AObuchow** [comment]
Awesome thank you! Btw, I have a windows machine but don't own a mac so having users test on OSX provides more value anyway :)
