### ISSUE TITLE
Generate p2 repo with Maven

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Eclipse-Modern-Dark-Theme#10]
It’d be a lot nicer to generate the p2 repo with maven, as is done for [Wild Web Developer](https://github.com/eclipse/wildwebdeveloper/blob/master/pom.xml). This would allow automatic deployment of the newest version of the plugin through GitHub Actions

**Comment by PyvesB** [comment]
Just as a heads up, I implemented a similar GitHub action for my Ruby plugin here: https://github.com/PyvesB/eclipse-solargraph

However, something recently changed with GitHub actions as the last two runs failed. Surprisingly, something seemed wrong with the `cp` command, but I haven't really had time to investigate further.

**Comment by AObuchow** [comment]
Awesome, thank you!

That's really helpful, I'll be basing my deployment action on the one you set up (and hopefully figure out what's going wrong with the cp command ;) )

**Comment by AObuchow** [comment]
Fixed in https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/pull/18, will make a separate issue to use GitHub actions.
