### ISSUE TITLE
It doesn't see any themes in the windows 10.

### ISSUE THREAD

**Issue by vel1024** [AObuchow/Eclipse-Modern-Dark-Theme#141]
- OS : Windows 10 Edu
- Eclipse : 2020-12

I downloaded this theme from eclipse marketplace.
But, I open preference, Any themes doesn't exist.

![theme-error2](https://user-images.githubusercontent.com/47293759/104271738-f08a4b00-54de-11eb-81bb-7d12e9f5d253.JPG)

I've reinstalled it several times, but I can't. What should I do?

**Comment by AObuchow** [comment]
@khusw sorry for the trouble!
I believe you're looking for the theme in the wrong place, it should be under General > Appearance (not General > Appearance > Colors and Fonts).

![image](https://user-images.githubusercontent.com/10300119/104324944-10f1df80-54b6-11eb-95c5-ba0020087085.png)
![image](https://user-images.githubusercontent.com/10300119/104324981-1e0ece80-54b6-11eb-9997-adfcf3313455.png)

After selecting "Spectrum" as your theme in Eclipse, press Apply and Close. You may also have to restart Eclipse for theme changes to take proper effect.

Let me know if this helps :)

**Comment by vel1024** [comment]
@AObuchow  Thank you, it works

![capture1](https://user-images.githubusercontent.com/47293759/104391909-5086fd00-5584-11eb-96db-e48747d6a6f2.JPG)

**Comment by AObuchow** [comment]
@khusw awesome, I'm glad to hear. Enjoy :)!
