### ISSUE TITLE
Scrollbars are always white on Windows 11

### ISSUE THREAD

**Issue by fabianlupa** [AObuchow/Eclipse-Modern-Dark-Theme#146]
On Windows 11 all scrollbars now use the light theme instead of the dark one. Probably more of an eclipse issue than a spectrum issue but maybe you have an idea on how to fix it?

Most other scrollbars I could find toggle their theme according to the Color Mode switch in the OS color customization settings (Light/Dark), except for programs that do not have a dark theme at all, notably notepad.exe.

![image](https://user-images.githubusercontent.com/5270359/141685760-0f0b3f0c-25a3-43ab-a5e8-bb7589f36d3d.png)

Same issue with the default dark theme in eclipse:

![image](https://user-images.githubusercontent.com/5270359/141685933-ba043d90-563b-4a2d-af39-c951dc8493c8.png)

This worked fine on Windows 10 (see screenshots in #137).

**Comment by AObuchow** [comment]
@flaiker thank you very much for the bug report.
I'm a bit caught up right now with finishing my university degree, but will look into this as soon as I can.

As you mentioned, if this bug exists in the default dark theme for Eclipse, it is most likely an upstream issue (and thus I will mark it as such).

Odds are, the Windows dark mode API (which is not official/public API IIRC) has changed between Windows 10 and 11, and thus the Windows SWT code to request dark scroll bars from the OS is broken on Windows 11.

A bug report should be made upstream on Eclipse's Bugzilla instance (or their newer bug trackers, if they are available).

**Comment by fabianlupa** [comment]
I think this might already have been fixed upstream. At least I found these recent changes:

https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/186454
https://bugs.eclipse.org/bugs/show_bug.cgi?id=576613

**Comment by AObuchow** [comment]
> I think this might already have been fixed upstream. At least I found these recent changes:
> 
> https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/186454 https://bugs.eclipse.org/bugs/show_bug.cgi?id=576613

That's awesome to hear - thank you for looking into that :) 
If you get a chance, please download the latest I-Build of Eclipse and let me know if the dark scroll bars are now fixed on Spectrum Theme.

**Comment by fabianlupa** [comment]
I could not get the integration build to work, sorry for the delay. However, 2021-12 has fixed the issue. :)

![image](https://user-images.githubusercontent.com/5270359/146671027-1077f89e-e09f-4d4f-abf3-10a68de33532.png)

**Comment by AObuchow** [comment]
@flaiker Thank you so much for getting back to me :) Glad to see it works in 2021-12!
