### ISSUE TITLE
Broken update site

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Eclipse-Modern-Dark-Theme#147]
As @PyvesB documented in https://github.com/PyvesB/eclipse-planet-themes/issues/8, hosting Spectrum Theme's update site using GitHub seems to not work anymore.

I'm quite busy with the last ~3 weeks of my undergraduate degree, but aim to fix this as soon as I get a moment.

@PyvesB seems to be using https://gitcdn.xyz to host his update site, as seen in https://github.com/PyvesB/eclipse-planet-themes/commit/33db153e95b682bc7a54d15a1eaaf51e81cae93a - this looks like a nice solution. 

However, it seems that https://gitcdn.xyz/ is currently down? In the event that gitcdn isn't a viable solution, another way to host the update site needs to be found.

**Comment by PyvesB** [comment]
They are somewhat flaky at times, but https://gitcdn.link seems to work well enough.

Alternatively, you could setup GitHub pages like I've done for this other plugin: https://github.com/PyvesB/eclipse-solargraph

**Comment by ingomohr** [comment]
Is the updatesite really broken? My updatesite that is served by the "raw" URL still works (at least in Eclipse).

**Comment by AObuchow** [comment]
> They are somewhat flaky at times, but https://gitcdn.link seems to work well enough.
> 
> Alternatively, you could setup GitHub pages like I've done for this other plugin: https://github.com/PyvesB/eclipse-solargraph

Thanks for the advice @PyvesB :) I think I will try out https://gitcdn.link first, although GitHub pages seems like it might be a more stable solution.

**Comment by AObuchow** [comment]
> Is the updatesite really broken? My updatesite that is served by the "raw" URL still works (at least in Eclipse).

@ingomohr Thank you for testing this and letting me know :) 
When I made this bug report it was because the Markplace downloads shields.io badges on the README of Spectrum Theme were reporting a broken update site (or something along those lines) but I hadn't actually tested the update site.

I just downloaded a fresh install of Eclipse & was able to successfully install Spectrum Theme off the Eclipse Marketplace :) So that's great!

I'm going to close this bug for now, although it's possible the update site will break in future updates/releases of Spectrum Theme and will have to be reopened.

**Comment by ingomohr** [comment]
Hey @AObuchow. Thanks for the update. Great to know installing from Marketplace still works fine. 

Btw: I'm pressing thumbs for your undergraduate degree. 😊

**Comment by AObuchow** [comment]
> Btw: I'm pressing thumbs for your undergraduate degree. blush

Thank you so much @ingomohr :) I'm looking forward to having more time for OSS contributions once I'm finished it! :sunglasses:

**Comment by PyvesB** [comment]
> When I made this bug report it was because the Markplace downloads shields.io badges on the README of Spectrum Theme were reporting a broken update site (or something along those lines) but I hadn't actually tested the update site.

This seems to have been a temporary wobble with the marketplace API, and is now resolved.

> I just downloaded a fresh install of Eclipse & was able to successfully install Spectrum Theme off the Eclipse Marketplace :) So that's great!

I'm not entirely sure that things are working as expected. The update site URL, https://raw.githubusercontent.com/AObuchow/Eclipse-Spectrum-Theme/updatesite/updatesite/ does return an invalid request. Installing on a fresh install of Eclipse is not necessarily sufficient: the `.p2` cache is shared by all Eclipse installations on your system, so if you had previously installed the latest version of Spectrum Theme on another Eclipse, the new one may well simply use the cached version and not actually hit the update site.

**Comment by ingomohr** [comment]
> the `.p2` cache is shared by all Eclipse installations on your system, so

Thanks for the hint, @PyvesB ! I just installed the feature from the Marketplace Client on a fresh machine that had no Eclipse installations before. Worked as expected, too.

**Comment by AObuchow** [comment]
> This seems to have been a temporary wobble with the marketplace API, and is now resolved.

Thanks for confirming this :)

> I'm not entirely sure that things are working as expected. The update site URL, https://raw.githubusercontent.com/AObuchow/Eclipse-Spectrum-Theme/updatesite/updatesite/ does return an invalid request.

You are right! Thank you for pointing this out to me.

> Installing on a fresh install of Eclipse is not necessarily sufficient: the `.p2` cache is shared by all Eclipse installations on your system, so if you had previously installed the latest version of Spectrum Theme on another Eclipse, the new one may well simply use the cached version and not actually hit the update site.

Good catch!  I hadn't considered the fact that I needed to clear my `.p2` cache.

**Comment by AObuchow** [comment]
> Thanks for the hint, @PyvesB ! I just installed the feature from the Marketplace Client on a fresh machine that had no Eclipse installations before. Worked as expected, too.

@ingomohr Thank you for the testing :) I'm a bit confused, when you say "Worked as expected, too" did you mean that the fresh Eclipse install (on a fresh machine) was able to successfully install Spectrum Theme from the Eclipse Marketplace?

If not, I will re-open this issue and try to make a patch very soon using git cdn since it seems to be the simplest solution for now.

**Comment by ingomohr** [comment]
> too" did you mean that the fresh Eclipse install (on a fresh machine) was able to successfully install Spectrum Theme from the Eclipse Marketplace?

Yep. That's what I wanted to say. 😊

**Comment by AObuchow** [comment]
> > too" did you mean that the fresh Eclipse install (on a fresh machine) was able to successfully install Spectrum Theme from the Eclipse Marketplace?
> 
> Yep. That's what I wanted to say. blush

Thank you for confirming - that's great to hear :) I'll keep the issue closed for now then, though I think the update site will soon have to be hosted in a different manner.
