### ISSUE TITLE
where could get offline install jar pkg

### ISSUE THREAD

**Issue by huanghx1990** [AObuchow/Eclipse-Modern-Dark-Theme#149]
as proposal， my working station could access internet,  but  i want to install the theme in my working linux station. where could I get the jar pkg?

**Comment by AObuchow** [comment]
Hey @huanghx1990 sorry for the delayed response, somehow I missed this.

I believe you should be able to download the `updatesite` directory from this repo's updatesite branch: https://github.com/AObuchow/Eclipse-Spectrum-Theme/tree/updatesite/updatesite

![image](https://github.com/AObuchow/Eclipse-Spectrum-Theme/assets/10300119/26684fe4-3478-4efc-9d87-d6d86787d5a1)

Click on "Download directory"

Then you can extract it on your system.

Next, open up Eclipse and on the menu bar click "Help" -> Install New Software....

You will see the install window appear. In the top right, click "Add...".
In the dialog that appears, click on `Local...` then find the directory where you extracted the Spectrum Theme updatesite. Be sure to give a memorable name in the name field and click "Add".

![image](https://github.com/AObuchow/Eclipse-Spectrum-Theme/assets/10300119/d2c1325b-6e01-48fc-a1b9-7d93aa4d3c9d)

Finally, back on the Install dialog, towards the top there is a drop-down that will list out all available updatesites. Find the one you just named and created and click on it.

You can then select Spectrum Theme to be installed, and click install/finish in the bottom right corner:

![image](https://github.com/AObuchow/Eclipse-Spectrum-Theme/assets/10300119/f76ad278-3bb7-4885-9c77-480b27722fc5)

I hope this helps :) 

I will be marking this issue as resolved, but please feel free to re-open if you encounter any issues.
