### ISSUE TITLE
Plugin has 2 licenses

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Eclipse-Modern-Dark-Theme#19]
Seems like two licenses appear when installing the plugin. Only the EPLv2 should be present.
![image](https://user-images.githubusercontent.com/10300119/84099463-ab95b780-a9d7-11ea-850e-7912432a372d.png)

**Comment by AObuchow** [comment]
The [feature.xml](https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/blob/master/Modern%20Dark%20Feature/feature.xml#L16) needs to be updated to use EPLv2

**Comment by mbooth101** [comment]
If you adopt tycho build, consider using the unified CBI license: https://wiki.eclipse.org/CBI#CBI_license_bundle

This way you will always have the latest text of the license without needing to duplicate the license content a bunch of times in your repo.

Let me know if you need any hints how to implement it :-)

**Comment by AObuchow** [comment]
Awesome! Thank you @mbooth101 :)

There's currently a PR to use a tycho build https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/pull/18 so I'm +1 for using the unified CBI license. Once that PR is merged I can begin working on using it. Seems like a much cleaner solution for this plugin's license.
