### ISSUE TITLE
Expandable-section headers on MANIFEST editor are painted black

### ISSUE THREAD

**Issue by ingomohr** [AObuchow/Eclipse-Modern-Dark-Theme#34]
<img width="771" alt="Screenshot 2020-06-11 at 14 09 34" src="https://user-images.githubusercontent.com/2838592/84383914-76fb4900-abed-11ea-8489-c35d24180667.png">

The section headers of the expandable sections on the "Dependencies" tab of the Manifest.MF editor are painted black and thus are hard to read.

Maybe this is something too, that we can improve with a next release ;)

Found in release version 1.0.6.

**Comment by AObuchow** [comment]
Thanks for catching this @ingomohr ! Will look into a fix :)
