### ISSUE TITLE
Screenshots on README are outdated

### ISSUE THREAD

**Issue by ingomohr** [AObuchow/Eclipse-Modern-Dark-Theme#35]
The screenshots on the readme are outdated. For instance, they show the read line on inactive tabs which has been removed w/ 1.0.6.

**Comment by AObuchow** [comment]
Good catch @ingomohr, will provide updated screenshots.

In the near future, it might be worth showing how the theme looks on all OS' platforms. You'll be able to help there with OSX screenshots ;)

**Comment by ingomohr** [comment]
> Good catch @ingomohr, will provide updated screenshots.
> 
> 
> 
> In the near future, it might be worth showing how the theme looks on all OS' platforms. You'll be able to help there with OSX screenshots ;)

Yup. I‘ll be glad to. 😉

**Comment by AObuchow** [comment]
Now that Modern Dark has it's own font & color preferences (eg. https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/pull/43#issuecomment-643080297) a note (with a picture) about it should be added to the README as well.

**Comment by AObuchow** [comment]
I should probably be posting this in a new bug, but here's a screenshot of the theme on Windows (for future reference). I modified the theme's colors to fit in with my Windows 10 theme.

![image](https://user-images.githubusercontent.com/10300119/84699392-6e717e00-af1f-11ea-9e24-ec322e6dc589.png)

**Comment by ingomohr** [comment]
> I should probably be posting this in a new bug, but here's a screenshot of the theme on Windows (for future reference). I modified the theme's colors to fit in with my Windows 10 theme.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/10300119/84699392-6e717e00-af1f-11ea-9e24-ec322e6dc589.png)
> 
> 

The screenshot looks nice. 😊
