### ISSUE TITLE
Progress bars in dialogues have light surroundings

### ISSUE THREAD

**Issue by PyvesB** [AObuchow/Eclipse-Modern-Dark-Theme#56]
Hello again!

I spotted a small issue with some progress bars on macOS:
<img width="570" alt="Screenshot 2020-06-16 at 11 54 21" src="https://user-images.githubusercontent.com/10694593/84760579-88b36680-afc8-11ea-9f4b-afcad9f55e5e.png">

As you can see, there's a not-quite-centred white rectangle around the progress bar. This only seems to happen for progress bars within dialogues, there is no issue with the ones in the Progress View for example.

As usual, let me know if you need any more information!

**Comment by AObuchow** [comment]
Thanks for reporting :) I had noticed this on Linux too but have yet to find the exact css required to fix it.
