### ISSUE TITLE
Javadoc is hard to Read

### ISSUE THREAD

**Issue by DKLEEE** [AObuchow/Eclipse-Modern-Dark-Theme#71]
Hi,
the Javadoc View, and Tooltip/Hover is very hard to read.
For me it is Black font on Black background. 
![grafik](https://user-images.githubusercontent.com/16030367/85275617-de808680-b480-11ea-938a-fbde668cb302.png)

There already has been an issue where it was to light.
https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/issues/13

Windows
Eclipse 2020-06
Plugin version 1.0.7.202006190441

**Comment by AObuchow** [comment]
Thanks for reporting @DKLEEE, I think I have an idea on how to fix this. Will keep you updated.

**Comment by AObuchow** [comment]
@DKLEEE can you update and confirm the issue is now fixed?

**Comment by AObuchow** [comment]
Also let me know if the issue also persists for Tooltip/Hover :)

**Comment by DKLEEE** [comment]
Looks good now, thanks :)

![grafik](https://user-images.githubusercontent.com/16030367/85521526-a86c0f80-b604-11ea-8143-05571041ea36.png)

**Comment by AObuchow** [comment]
@DKLEEE awesome thanks! You wouldn’t happen to know if the java doc scroll bars on Windows are also light on the platform dark theme like in the screenshot you sent?

**Comment by DKLEEE** [comment]
I also noticed that.
Yes, the default Dark theme has the same Problem, so i wouldn't bother you here ;)
